#token过期时间，单位秒
token-overtime: 1800
#请求uri白名单
pass-path: "hello,getVCode,checkUserId,front,login"

server:
  port: 80

spring:
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
#    default-property-inclusion: non_null
  redis:
    timeout: 15000
    #单机
    host: localhost
    port: 6379
    password:
    #cluster集群配置（首先要在linux搭建好主从复制（三主三从）、哨兵模式监听master、cluster集群）
#    cluster:
      #重定向的最大数量，比如第一台挂了，连第二台，第二台挂了连第三台
#      max-redirects: 3
      #redis节点：ip+port
#      nodes: 192.168.10.111:6379,192.168.10.111:6380,192.168.10.111:6381,192.168.10.111:6382,192.168.10.111:6383,192.168.10.111:6384
  #数据库
  datasource:
    username: root
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fu.demo.entity

#showSql
logging:
  level:
    #生产环境可以改为info
    com.fu.demo.mapper: debug
