#token过期时间，单位秒
token-overtime: 1800
#请求uri白名单
pass-uri:
  not-check:
    - hello
    - getVCode
    - checkUserId
    - front
    - login
    - minio/upload
    - minio/delete
    - fileUpload
    - fileDelete
    - roundRobin
    - user/select

server:
  port: 81

spring:
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
#    default-property-inclusion: non_null
  redis:
    timeout: 15000
    #单机
    host: localhost
    port: 6379
    password:
    #cluster集群配置（首先要在linux搭建好主从复制（三主三从）、哨兵模式监听master、cluster集群）
#    cluster:
      #重定向的最大数量，比如第一台挂了，连第二台，第二台挂了连第三台
#      max-redirects: 3
      #redis节点：ip+port
#      nodes: 192.168.10.111:6379,192.168.10.111:6380,192.168.10.111:6381,192.168.10.111:6382,192.168.10.111:6383,192.168.10.111:6384
  #数据库
  datasource:
    username: jettwork
    password: jettwork
    #url中database为对应的数据库名称
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #双机热备数据库
    mysql1:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
      # 初始连接数
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 1
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      keepAlive: true

    mysql2:
      url: jdbc:mysql://192.168.18.253:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
      # 初始连接数
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 1
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      keepAlive: true
    #监控信息配置
    monitor:
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fu.demo.entity

#showSql
logging:
  level:
    #生产环境可以改为info
    com.fu.demo.mapper: debug

minio:
  endpoint: http://192.168.18.253
  port: 9000
  secure: false
  accessKey: minioadmin
  secretKey: minioadmin

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.10.111:22122
    - 192.168.10.112:22122